# Generated by Django 5.2.6 on 2025-09-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('lien_affiliation', models.URLField()),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
